<?php
/**
 * BuddyBoss Crack.
 *
 * @package BuddyBoss\Core
 * @since BuddyBoss 1.2.9
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_A' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_A', 'a' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_D' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_D', 'd' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_M' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_M', 'm' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_I' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_I', 'i' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_N' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_N', 'n' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_T' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_T', 't' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_A' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_A', 'a' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_F' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_F', 'f' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_T' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_T', 't' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_E' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_E', 'e' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_R' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_R', 'r' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_S' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_S', 's' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_W' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_W', 'w' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_I' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_I', 'i' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_C' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_C', 'c' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_H' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_H', 'h' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_M' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_M', 'm' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_P' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_P', 'p' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_R' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_R', 'r' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E', 'e' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S', 's' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T', 't' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_I' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_I', 'i' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_A' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_A', 'a' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_N' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_N', 'n' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_U' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_U', 'u' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_D' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_D', 'd' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_H' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_H', 'h' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_M' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_M', 'm' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S', 's' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_I' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_I', 'i' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T', 't' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E', 'e' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_R' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_R', 'r' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_A' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_A', 'a' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_N' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_N', 'n' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_U' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_U', 'u' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_D' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_D', 'd' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_H' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_H', 'h' );
}
if ( ! defined( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_M' ) ) {
	define( 'BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_M', 'm' );
}

if ( ! function_exists( 'decfdf2bf8157a6391ba2a91cc2ccf7' ) ) {
	function decfdf2bf8157a6391ba2a91cc2ccf7() {
		if ( ! function_exists( 'buddyboss_theme' ) ) {
			return;
		}

		if ( is_multisite() ) {
			$saved_licenses = get_site_option( 'bboss_updater_saved_licenses' );
		} else {
			$saved_licenses = get_option( 'bboss_updater_saved_licenses' );
		}
		$license_is_there          = false;
		$license_is_there_inactive = false;
		if ( ! empty( $saved_licenses ) ) {
			foreach ( $saved_licenses as $package_id => $license_details ) {
				if ( ! empty( $license_details['license_key'] ) && ! empty( $license_details['product_keys'] ) && is_array( $license_details['product_keys'] ) && in_array( 'BB_THEME', $license_details['product_keys'] ) ) {
					$license_is_there = true;
					if ( isset( $license_details['is_active'] ) && false === $license_details['is_active'] ) {
						$license_is_there_inactive = true;
					}
				}
			}
		}
		if ( ! $license_is_there && ! $license_is_there_inactive ) {
			if ( is_multisite() ) {
				update_site_option( 'be5f330bbd49d6160ff4658ac3d219ee', '1' );
			} else {
				update_option( 'be5f330bbd49d6160ff4658ac3d219ee', '1' );
			}
		} else {
			if ( is_multisite() ) {
				delete_site_option( 'be5f330bbd49d6160ff4658ac3d219ee' );
			} else {
				delete_option( 'be5f330bbd49d6160ff4658ac3d219ee' );
			}
		}
	}

	add_action( BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_A . BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_D . BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_M . BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_I . BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_N . '_' . BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_I . BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_N . BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_I . BUDDYBOSS_THEME_WORDPRESS_ADMIN_INIT_HOOK_T, 'decfdf2bf8157a6391ba2a91cc2ccf7', 999999 );
	add_action( BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_A . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_F . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_E . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_R . '_' . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_S . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_W . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_I . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_C . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_H . '_' . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_H . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_E . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_M . BUDDYBOSS_THEME_WORDPRESS_AFTER_SWITCH_THEME_HOOK_E, 'decfdf2bf8157a6391ba2a91cc2ccf7' );
}

if ( ! function_exists( 'ebd86f7edab33d9b6e36a95a6dd674a5' ) ) {
	function ebd86f7edab33d9b6e36a95a6dd674a5( $transient ) {
		decfdf2bf8157a6391ba2a91cc2ccf7();

		return $transient;
	}

	add_filter( BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_P . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_R . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . '_' . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . '_' . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_I . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . '_' . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_R . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_A . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_N . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_I . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_N . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . '_' . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_U . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_P . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_D . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_A . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . '_' . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_H . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_M . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . BUDDYBOSS_THEME_WORDPRESS_PRE_SET_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S, 'ebd86f7edab33d9b6e36a95a6dd674a5' );
	add_filter( BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_I . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . '_'  . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_R . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_A . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_N . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_I . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_N . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . '_' . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_U . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_P . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_D . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_A . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . '_' . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_T . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_H . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_M . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_E . BUDDYBOSS_THEME_WORDPRESS_SITE_TRANSIENT_UPDATE_THEMES_HOOK_S, 'ebd86f7edab33d9b6e36a95a6dd674a5' );
}

