# Travis CI Configuration File

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php
node_js:
  - 8
  - 10

dist: trusty

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm
    - /tmp/node

git:
  depth: 10

php:
  - 7.3
  #- 7.2
  #- 5.6

# WordPress comes from the Git mirror, where 'master' mirrors svn 'trunk' and
# x.y mirrors the latest from the x.y branch
#env:
#  - WP_VERSION=master BP_TRAVISCI=travis:phpunit
#  - WP_VERSION=5.2 BP_TRAVISCI=travis:phpunit
#  - WP_VERSION=5.1 BP_TRAVISCI=travis:phpunit
#  - WP_VERSION=5.0 BP_TRAVISCI=travis:phpunit
#  - WP_VERSION=4.9 BP_TRAVISCI=travis:phpunit
#  - WP_VERSION=4.8 BP_TRAVISCI=travis:phpunit
#  - WP_VERSION=4.7 BP_TRAVISCI=travis:phpunit
env:
  - WP_VERSION=master BP_TRAVISCI=travis:grunt
#  - WP_VERSION=5.2 BP_TRAVISCI=travis:grunt
#  - WP_VERSION=5.1 BP_TRAVISCI=travis:grunt
#  - WP_VERSION=5.0 BP_TRAVISCI=travis:grunt
#  - WP_VERSION=4.9 BP_TRAVISCI=travis:grunt
#  - WP_VERSION=4.8 BP_TRAVISCI=travis:grunt
#  - WP_VERSION=4.7 BP_TRAVISCI=travis:grunt

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=master BP_TRAVISCI=travis:grunt
      #env: WP_VERSION=master BP_TRAVISCI=travis:grunt SNIFF=1
#    - php: 7.3
#      env: WP_VERSION=master BP_TRAVISCI=travis:grunt
#      #env: WP_VERSION=master BP_TRAVISCI=travis:phpcompat
#    - php: 5.3
#      env: WP_VERSION=4.8 BP_TRAVISCI=travis:grunt
#      #env: WP_VERSION=4.8 BP_TRAVISCI=travis:phpunit
#      dist: precise
#    - php: 5.3
#      env: WP_VERSION=4.7 BP_TRAVISCI=travis:grunt
#      #env: WP_VERSION=4.7 BP_TRAVISCI=travis:phpunit
#      dist: precise
#  exclude:
#    - php: 7.3
#      env: WP_VERSION=4.9 BP_TRAVISCI=travis:grunt
#      #env: WP_VERSION=4.9 BP_TRAVISCI=travis:phpunit
#    - php: 7.3
#      env: WP_VERSION=4.8 BP_TRAVISCI=travis:grunt
#      #env: WP_VERSION=4.8 BP_TRAVISCI=travis:phpunit
#    - php: 7.3
#      env: WP_VERSION=4.7 BP_TRAVISCI=travis:grunt
#      #env: WP_VERSION=4.7 BP_TRAVISCI=travis:phpunit
#    - php: 7.3
#      env: WP_VERSION=master BP_TRAVISCI=travis:grunt
      #env: WP_VERSION=master BP_TRAVISCI=travis:phpunit

# before_install: Failures in this section will result in build status 'errored'
before_install:
  # set up WP install
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR
  - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  - plugin_slug=$(basename $(pwd))
  - plugin_dir=$WP_DEVELOP_DIR/src/wp-content/plugins/$plugin_slug
  - cd ..
  - mv $plugin_slug $plugin_dir
  - |
    # Remove Xdebug for a huge performance increase:
    if [[ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]]; then
      phpenv config-rm xdebug.ini
    fi

  # set up phpcs
  - if [[ "$SNIFF" == "1" ]]; then export PHPCS_DIR=/tmp/phpcs; fi
  - if [[ "$SNIFF" == "1" ]]; then export SNIFFS_DIR=/tmp/sniffs; fi
  # Install PHP_CodeSniffer.
  - if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR; fi
  # Install WordPress Coding Standards.
  - if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/WordPress/WordPress-Coding-Standards.git $SNIFFS_DIR; fi
  # Set install path for WordPress Coding Standards.
  - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/bin/phpcs --config-set installed_paths $SNIFFS_DIR; fi
  # After CodeSniffer install you should refresh your path.
  - if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi

  # set up tests config
  - cd $WP_DEVELOP_DIR
  - echo $WP_DEVELOP_DIR
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php

  # set up database
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot

  # prepare for running the tests
  - cd $plugin_dir

  # setup NodeJS version using NVM
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - node --version
  - nvm install 14
  - node --version
  - npm install -g grunt-cli
  - npm --version
  - mysql --version
  - phpenv versions
  - php --version
  - php -m
  - phpunit --version
  - curl --version
  - grunt --version
  - git --version
  - svn --version

# before_script: Failures in this section will result in build status 'errored'
before_script:
  - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/bin/phpcs -p . --standard=WordPress --ignore=*/vendor/* src/; fi
#  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then composer global require --dev phpunit/phpunit ^4; fi
#  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer global require --dev phpunit/phpunit ^5; composer install; fi
#  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then composer global require --dev phpunit/phpunit ^6; composer install; fi
#  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then composer global require --dev phpunit/phpunit ^6; composer install; fi
  - mkdir -p /tmp/node/node_modules
  - ln -s /tmp/node/node_modules $plugin_dir/node_modules
  - npm install
  - npm rebuild node-sass

# Run tests
script: grunt $BP_TRAVISCI

notifications:
  email: false
