name: NodeJS with Grunt

on:
  push:
    branches: 
      - "release"
      - "main"
      - "master"
  pull_request:
    branches:
      - "release"
      - "main"
      - "master"
  # Enable manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: |
        npm install --no-package-lock
        npm install grunt-cli -g
      
    - name: Display npm and node versions
      run: |
        npm -v
        node -v
        
    - name: List installed packages
      run: npm list --depth=0

    - name: Run Grunt
      run: grunt
      
    - name: Upload npm logs if failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: npm-logs
        path: ~/.npm/_logs/
