name: NodeJS with Grunt

on:
  push:
    branches: 
      - "release"
      - "main"
      - "master"
  pull_request:
    branches:
      - "release"
      - "main"
      - "master"
  # Enable manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build
      run: |
        npm ci
        grunt
