name: NodeJS with Grunt

on:
  push:
    branches:
      - "release"
      - "main"
      - "master"
  pull_request:
    branches:
      - "release"
      - "main"
      - "master"
  # Enable manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Set npm version for Node 14
      if: matrix.node-version == '14.x'
      run: |
        npm install -g npm@6.14.18
        npm cache clean --force

    - name: Install Grunt CLI
      run: npm install -g grunt-cli

    - name: Install specific dependencies first
      run: |
        npm install grunt@1.6.1 --save-dev
        npm install stylelint@13.13.0 --save-dev
        npm install cosmiconfig@8.0.0 --save-dev
        npm install js-yaml@4.1.0 --save-dev
        npm install parse-json@5.2.0 --save-dev
        npm install path-type@4.0.0 --save-dev
        npm install argparse@2.0.1 --save-dev
        npm install stylelint-config-recommended-scss@4.3.0 --save-dev
        npm install stylelint-scss@3.21.0 --save-dev
        npm install stylelint-config-recommended@5.0.0 --save-dev

    - name: Install remaining dependencies
      run: npm install --legacy-peer-deps --no-audit

    - name: Display npm and node versions
      run: |
        npm -v
        node -v

    - name: List installed packages
      run: npm list --depth=0

    - name: Run Grunt
      run: grunt
